server:
  port: 8082
spring:
 datasource:
  url: jdbc:mariadb://localhost:3306/api-amigos?createDatabaseIfNotExist=true
  username: root
  password: root
  driver-class-name: org.mariadb.jdbc.Driver
  initialization-mode: always
 jpa:
   open-in-view: false
   database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
   generate-ddl: true
   hibernate:
     naming:
       physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
       implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
   properties:
     hibernate:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      show_sql: true
      format_sql: true
logging:
  level:
    org:
      hibernate:
        type: info
security: 
 oauth2: 
  resource: 
   token-info-uri: http://localhost:9191/oauth/check_token #https://svld-nam02.pgr.mpf.mp.br/nidp/oauth/nam/tokeninfo
  client:
   client-id: mobile #ac198936-859e-4105-b308-0f6b02744fa3
   client-secret: root #96BfDDjnbVq0Zj4C4HDKW3Bu3NL2_g5Mdigw10mX0nwFgXlxlChT5Ss4hGGtyU7NDFd2BZZF_WvoQ0JRZexTVw
